version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: aiohttp
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: aiohttp
    ports:
      - 5434:5432
